name: Flet Build APK

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: 3.11
  FLUTTER_VERSION: 3.20.0  # Update to a Flutter version that includes Dart SDK >=3.4.0
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install flet requests Pillow PyInstaller

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install Linux Build Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip build-essential libssl-dev libffi-dev python3-dev libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libtiff5-dev tk-dev tcl-dev libopenjp2-7-dev libwebp-dev libharfbuzz-dev libfribidi-dev libxcb1-dev ninja-build libgtk-3-dev

    - name: Install Android SDK and Build Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
        sudo mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        sudo unzip -q commandlinetools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/latest
        sudo rm commandlinetools.zip
        echo "export PATH=\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:\$ANDROID_SDK_ROOT/platform-tools:\$PATH" >> $GITHUB_ENV
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;35.0.0" "platforms;android-33"

    - name: Flutter Doctor
      run: flutter doctor

    - name: Flet Build APK
      run: |
        flutter config --no-analytics
        flet build apk

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk-build-artifact
        path: build/app/outputs/flutter-apk/app-release.apk
        if-no-files-found: warn
