name: Flet Build APK

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: 3.8  # Using Python 3.8 for compatibility
  FLUTTER_VERSION: 3.22.2
  ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Update pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Show requirements.txt
      run: cat requirements.txt

    - name: Install Required System Libraries for Pillow
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
          libjpeg-dev \
          zlib1g-dev \
          libtiff-dev \
          libfreetype6-dev \
          liblcms2-dev \
          libwebp-dev \
          libopenjp2-7-dev \
          libharfbuzz-dev \
          libfribidi-dev \
          libxcb1-dev \
          tk-dev \
          tcl-dev \
          libffi-dev \
          build-essential \
          pkg-config

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        pip install flet
        pip install "pillow==8.2.0"  # Use a specific compatible version of Pillow

    - name: List installed Python packages
      run: |
        source venv/bin/activate
        pip list

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install Linux Build Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev

    - name: Install Android SDK and Build Tools
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O commandlinetools.zip
        sudo mkdir -p $ANDROID_SDK_ROOT/cmdline-tools/latest
        sudo unzip -q commandlinetools.zip -d $ANDROID_SDK_ROOT/cmdline-tools/latest
        sudo rm commandlinetools.zip
        echo "export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV
        source $GITHUB_ENV
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;35.0.0" "platforms;android-33"

    - name: Debug Flutter Installation
      run: flutter doctor -v

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Flet Build APK
      run: |
        source venv/bin/activate
        which flet  # Check if flet is in the path
        flet build apk --verbose --build-number=${{ env.BUILD_NUMBER }} --build-version=${{ env.BUILD_VERSION }}

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4.3.4
      with:
        name: apk-build-artifact
        path: build/app/outputs/flutter-apk/app-release.apk
        if-no-files-found: warn
        overwrite: false
