name: Build Flet App to APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Flet CLI
      - name: Install Flet CLI
        run: |
          pip install flet

      # Build the APK
      - name: Build APK
        run: |
          flet pack main.py --target android

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: CaptchaSolver-APK
          path: dist/*.apk
