name: Build Windows Executable

on:
  push:
    branches:
      - main  # يتم تشغيل الـ Workflow عند دفع التغييرات على الفرع الرئيسي
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # الإصدار المناسب

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Install PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # 5. Build the executable
      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole app/main.py

      # 6. Upload artifact (executable file)
      - name: Upload executable
        uses: actions/upload-artifact@v3
        with:
          name: app-executable
          path: dist/main.exe  # مسار الملف التنفيذي الناتج
