name: Windows CI/CD for Captcha Solver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install opencv-python-headless
        pip install torch torchvision
        pip install openvino-dev
        pip install pillow requests numpy
        
    # Step 4: Validate OpenVINO installation
    - name: Verify OpenVINO installation
      run: |
        python -c "from openvino.runtime import Core; print('OpenVINO Installed Successfully')"

    # Step 5: Run the application
    - name: Run Application
      run: |
        python main.py

    # Step 6: Run Linter (Optional)
    - name: Run Linter
      run: |
        pip install flake8
        flake8 --max-line-length=120 .
