name: Build and Save EXE Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        pip install opencv-python-headless torch torchvision openvino-dev pillow requests numpy

    # Step 4: Build EXE using PyInstaller
    - name: Package Application as EXE
      run: |
        pyinstaller --onefile --name CaptchaSolverApp main.py

    # Step 5: Save EXE as Artifact
    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v3
      with:
        name: CaptchaSolverApp
        path: dist/CaptchaSolverApp.exe
