name: Build EXE for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install base64 torch torchvision openvino-dev numpy opencv-python Pillow requests tk
        pip install pyinstaller

    - name: Package as EXE
      run: |
        pyinstaller --onefile --noconsole --name CaptchaApp main.py

    - name: Upload EXE Artifact
      uses: actions/upload-artifact@v3
      with:
        name: CaptchaApp
        path: dist/CaptchaApp.exe
