name: Build Windows Desktop Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
                  pip install openvino-dev
                  pip install torch torchvision
                  pip install numpy
                  pip install  opencv-python
                  pip install pillow
                  pip install requests
                  pip install PyInstaller
                  pip install openvino
# تثبيت المتطلبات من requirements.txt

      - name: Build executable with PyInstaller
        run: |
          pip install pyinstaller  # تأكد من تثبيت PyInstaller
          pyinstaller --onefile --windowed --name salkhhm main.py

      - name: List dist directory contents
        run: dir dist

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: salkhhm-Executable
          path: dist/salkhhm.exe
